[package]
name = "diem-forge"
description = "Diem end to end test framework"
version = "0.0.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
again = { workspace = true }
anyhow = { workspace = true, features = ["backtrace"] }
diem = { workspace = true }
diem-cached-packages = { workspace = true }
diem-cli-common = { workspace = true }
diem-config = { workspace = true }
diem-db = { workspace = true }
diem-framework = { workspace = true }
diem-genesis = { workspace = true }
diem-global-constants = { workspace = true }
diem-infallible = { workspace = true }
diem-inspection-service = { workspace = true }
diem-logger = { workspace = true }
diem-rest-client = { workspace = true }
diem-retrier = { workspace = true }
diem-sdk = { workspace = true }
diem-secure-storage = { workspace = true }
diem-short-hex-str = { workspace = true }
diem-state-sync-driver = { workspace = true }
diem-transaction-emitter-lib = { workspace = true }
diem-transaction-generator-lib = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["env", "unstable-styles"] }
either = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hyper = { workspace = true }
hyper-tls = { workspace = true }
itertools = { workspace = true }
json-patch = { workspace = true }
k8s-openapi = { version = "0.13.1", default-features = false, features = [
    "v1_22",
] }
kube = { version = "0.65.0", default-features = false, features = [
    "jsonpatch",
    "client",
    "rustls-tls",
] }
num_cpus = { workspace = true }
once_cell = { workspace = true }
prometheus-http-query = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tempfile = { workspace = true }
termcolor = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

[features]
default = []
testing = ["diem-global-constants/testing"]
