[package]
name = "diem-vm"
description = "Diem VM runtime"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
diem-aggregator = { workspace = true }
diem-block-executor = { workspace = true }
diem-block-partitioner = { workspace = true }
diem-crypto = { workspace = true }
diem-crypto-derive = { workspace = true }
diem-framework =  { workspace = true }
diem-gas = { workspace = true }
diem-infallible = { workspace = true }
diem-logger = { workspace = true }
diem-metrics-core = { workspace = true }
diem-move-stdlib = { workspace = true }
diem-mvhashmap = { workspace = true }
diem-state-view = { workspace = true }
diem-types = { workspace = true }
diem-utils = { workspace = true }
diem-vm-logging = { workspace = true }
diem-vm-types = { workspace = true }
bcs = { workspace = true }
dashmap = { workspace = true }
fail = { workspace = true }
futures = { workspace = true }
move-binary-format = { workspace = true }
move-bytecode-utils = { workspace = true }
move-bytecode-verifier = { workspace = true }
move-core-types = { workspace = true }
move-table-extension = { workspace = true }
move-unit-test = { workspace = true, optional = true }
move-vm-runtime = { workspace = true }
move-vm-test-utils = { workspace = true }
move-vm-types = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
ouroboros = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
smallvec = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
diem-language-e2e-tests = { workspace = true }
diem-types = { workspace = true }
proptest = { workspace = true }

[features]
default = []
mirai-contracts = []
fuzzing = ["move-core-types/fuzzing", "move-binary-format/fuzzing", "move-vm-types/fuzzing", "diem-framework/fuzzing"]
failpoints = ["fail/failpoints", "move-vm-runtime/failpoints"]
testing = ["move-unit-test", "diem-framework/testing"]
